alias l="ls -lA"
alias g="git"
alias lg="l | grep -i"
alias c="pbcopy"
alias k="kubectl"
alias kcp="connect_to_first_pod_by_name"
alias dbt="docker build -t"
alias d="docker"
alias av="aws-vault"
alias avm='av exec -t $(op item get "AWS goingcloud" --otp)'
alias lens='open -a /Applications/Freelens.app'
alias awslocal="aws --profile=local --endpoint-url=http://localhost:4566"
alias dc="docker compose"
alias dcd="docker compose down"
alias dcud="docker compose up -d"
alias dcudb="docker compose up -d --build"