PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
PATH="$PATH:/opt/homebrew/opt/mysql-client/bin"
PATH="/opt/homebrew/opt/node@16/bin:$PATH"
PATH="/opt/homebrew/bin:$PATH"
